receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  # Data sources: metrics
  prometheus:
    endpoint: otel-collector:8889

service:
  pipelines:
    metrics:
      receivers: [ otlp ]
      exporters: [ prometheus ]
