global:
  scrape_interval: 5s
  evaluation_interval: 30s

scrape_configs:
  - job_name: prometheus
    honor_labels: true
    static_configs:
      - targets: ["otel-collector:8888", "otel-collector:8889"]
